import { useAnimations, useGLTF, useScroll } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { useEffect, useRef } from "react";
import { Group, Vector3 } from "three";
import { GLTF } from "three-stdlib"; // Add this import


// Define a custom GLTF type interface
interface CustomGLTF extends GLTF {
  nodes: Record<string, any>;
  materials: Record<string, any>;
  animations: any[];
}

useGLTF.preload("/buster_drone.glb");

interface ModelProps {
  isMobile: boolean;
}

export default function Model({ isMobile }: ModelProps) {
  const group = useRef<Group>(null);
  const modelPosition = useRef<Vector3>(new Vector3(10, 0.16, 10)); // Initial position for web
  const { nodes, materials, animations, scene } = useGLTF("/buster_drone.glb") as CustomGLTF;
  const { actions } = useAnimations(animations, scene);
  const liftoffAction = actions ? actions["Start_Liftoff"] : null;
  const scroll = useScroll();
  const { viewport } = useThree();

  useEffect(() => {
    if (liftoffAction) {
      liftoffAction.play();
    } else {
      console.warn("Animation 'Start_Liftoff' not found.");
    }

    // Set the initial position and scale of the model
    if (group.current) {
      if (isMobile) {
        const mobileX = 6.3 + viewport.width / 4;
        const mobileY = -3.1 + viewport.height / 4;
        modelPosition.current.set(mobileX, mobileY, 0);
        group.current.position.copy(modelPosition.current);
        group.current.scale.set(0.1, 0.2, 0.1);
      } else {
        group.current.position.copy(modelPosition.current);
        group.current.scale.set(0.8, 0.8, 0.8);
      }
    }
  }, [liftoffAction, isMobile, viewport]);

  useFrame((state, delta) => {
    if (liftoffAction) {
      const clipDuration = liftoffAction.getClip().duration;
      liftoffAction.time = (liftoffAction.time + delta) % clipDuration;
    }

    if (group.current) {
      if (isMobile) {
        // Mobile: Update model position based on scroll and viewport
        const scrollMultiplier = 10; // Increase this value to make movement more dramatic
        const targetX = 6.4 + viewport.width / 4 + scroll.offset * scrollMultiplier * viewport.width;
        const targetY = -3.1 + viewport.height / 4 + scroll.offset * scrollMultiplier * viewport.height / 2;

        // Clamp targetX and targetY to keep the drone on screen
        const clampedX = Math.max(-viewport.width / 2, Math.min(viewport.width / 2, targetX));
        const clampedY = Math.max(-viewport.height / 2, Math.min(viewport.height / 2, targetY));

        // Smoothly interpolate position
        modelPosition.current.lerp(new Vector3(clampedX+5.5, clampedY, 0), 0.03);
        group.current.position.copy(modelPosition.current);
        // console.log(modelPosition)
        // Smoothly interpolate scale
        const targetScale = 0.3;
        group.current.scale.lerp(new Vector3(targetScale+0.2, targetScale+0.2, targetScale+0.2), 0.1);

        // Adjust rotation for mobile
        const targetRotationY = -Math.PI / 3;
        group.current.rotation.y += (targetRotationY - group.current.rotation.y) * 0.1;
      } else {
        // Web: Update model position based on original logic
        const x = 10 + scroll.offset * 20;
        const y = -1;
        modelPosition.current.set(x, y, 0);
        group.current.position.copy(modelPosition.current);
      }
    }
  });

  return (
    <group ref={group} dispose={null} rotation={[0, isMobile ? 0 : -Math.PI * 40 / 180, 0]}>
      <primitive object={scene} />
    </group>
  );
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'

// export default function Model(props) {
//   const group = useRef()
//   const { nodes, materials, animations } = useGLTF('/buster_drone.glb')
//   const { actions } = useAnimations(animations, group)
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Scene">
//         <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.01308184}>
//           <group name="BusterDronefbx" rotation={[Math.PI / 2, 0, 0]}>
//             <group name="Object_2">
//               <group name="RootNode">
//                 <group name="Drone_Controller">
//                   <group name="Turbine_Controller" position={[0, -100, -4.99999905]}>
//                     <group
//                       name="Turbine_L"
//                       position={[-12.24479961, 0.0000056, -1.00702012]}
//                       rotation={[Math.PI / 2, 0, 0]}
//                     />
//                     <group
//                       name="Turbine_R"
//                       position={[12.24479961, 0.0000056, -1.00702012]}
//                       rotation={[Math.PI / 2, 0, 0]}
//                     />
//                   </group>
//                   <group
//                     name="U_MassPoint"
//                     position={[0, 0.11856791, -12.91004658]}
//                     rotation={[1.32056008, 0, 0]}>
//                     <group name="D_MassPoint" position={[0, 0, 77.5]}>
//                       <group
//                         name="Drone_Body"
//                         position={[0, 0, -37.5]}
//                         rotation={[-Math.PI / 2, 0, 0]}>
//                         <mesh
//                           name="Drone_Body_body_0"
//                           castShadow
//                           receiveShadow
//                           geometry={nodes.Drone_Body_body_0.geometry}
//                           material={materials.body}
//                         />
//                         <group
//                           name="Drone_Gen_L"
//                           position={[19.23712921, -26.57673073, -0.74819756]}
//                           rotation={[Math.PI / 2, 1.02974445, -Math.PI / 2]}>
//                           <mesh
//                             name="Drone_Gen_L_body_0"
//                             castShadow
//                             receiveShadow
//                             geometry={nodes.Drone_Gen_L_body_0.geometry}
//                             material={materials.body}
//                             position={[0.00000334, 0, 0.00000343]}
//                           />
//                           <group
//                             name="Drone_Panel_L"
//                             position={[-0.67849445, -0.37588584, 1.95770931]}
//                             rotation={[0.00042457, 0, 0]}>
//                             <group
//                               name="Drone_leg_L"
//                               position={[12.88695431, -9.6108036, -0.72929537]}
//                               rotation={[-1.2391841, -Math.PI / 2, 0]}>
//                               <mesh
//                                 name="Drone_leg_L_leg_0"
//                                 castShadow
//                                 receiveShadow
//                                 geometry={nodes.Drone_leg_L_leg_0.geometry}
//                                 material={materials.material}
//                               />
//                               <group
//                                 name="L_P1_G"
//                                 position={[-2.41547441, -4.84228373, -0.00663747]}
//                                 rotation={[Math.PI, -1.41081881, Math.PI]}>
//                                 <mesh
//                                   name="L_P1_G_leg_0"
//                                   castShadow
//                                   receiveShadow
//                                   geometry={nodes.L_P1_G_leg_0.geometry}
//                                   material={materials.material}
//                                   position={[-0.00000215, 0.00000489, 0]}
//                                 />
//                                 <group
//                                   name="L_P2"
//                                   position={[-0.00000215, 0.00000489, 0]}
//                                   rotation={[1.28319657, 0, 0]}>
//                                   <mesh
//                                     name="L_P2_leg_0"
//                                     castShadow
//                                     receiveShadow
//                                     geometry={nodes.L_P2_leg_0.geometry}
//                                     material={materials.material}
//                                     position={[0.00000453, -0.00000417, -0.00002199]}
//                                   />
//                                   <group
//                                     name="L_P3_G"
//                                     position={[0.00026894, -22.91594696, 0.02673775]}>
//                                     <mesh
//                                       name="L_P3_G_leg_0"
//                                       castShadow
//                                       receiveShadow
//                                       geometry={nodes.L_P3_G_leg_0.geometry}
//                                       material={materials.material}
//                                       position={[0.00000238, 0.00000381, -0.00001144]}
//                                     />
//                                     <group
//                                       name="L_P4"
//                                       position={[-0.00445938, 0.00000827, 0.00004917]}
//                                       rotation={[1.46490993, -2e-8, Math.PI]}>
//                                       <mesh
//                                         name="L_P4_leg_0"
//                                         castShadow
//                                         receiveShadow
//                                         geometry={nodes.L_P4_leg_0.geometry}
//                                         material={materials.material}
//                                         position={[0, 0.0000087, -0.00000241]}
//                                       />
//                                       <group
//                                         name="L_P5_M"
//                                         position={[0.05687618, -11.23663044, 0.08181404]}
//                                         rotation={[0.00002554, 0.00000757, -0.02184239]}>
//                                         <mesh
//                                           name="L_P5_M_leg_0"
//                                           castShadow
//                                           receiveShadow
//                                           geometry={nodes.L_P5_M_leg_0.geometry}
//                                           material={materials.material}
//                                           position={[0, 0.00001633, 0]}
//                                         />
//                                         <group
//                                           name="L_P6_G"
//                                           position={[0.14344198, -9.37102985, -0.08200215]}>
//                                           <mesh
//                                             name="L_P6_G_leg_0"
//                                             castShadow
//                                             receiveShadow
//                                             geometry={nodes.L_P6_G_leg_0.geometry}
//                                             material={materials.material}
//                                             position={[0, 0.0000126, -0.0000033]}
//                                           />
//                                           <group
//                                             name="L_P7"
//                                             position={[0.01226425, 0.00025447, 0.00025468]}
//                                             rotation={[Math.PI / 2, 0, 0]}>
//                                             <mesh
//                                               name="L_P7_leg_0"
//                                               castShadow
//                                               receiveShadow
//                                               geometry={nodes.L_P7_leg_0.geometry}
//                                               material={materials.material}
//                                               position={[-0.00000262, 0.00000286, -0.0000151]}
//                                             />
//                                           </group>
//                                         </group>
//                                       </group>
//                                     </group>
//                                   </group>
//                                 </group>
//                               </group>
//                             </group>
//                             <mesh
//                               name="Drone_Panel_L_body_0"
//                               castShadow
//                               receiveShadow
//                               geometry={nodes.Drone_Panel_L_body_0.geometry}
//                               material={materials.body}
//                               position={[0, -0.00000441, -0.00000405]}
//                             />
//                           </group>
//                         </group>
//                         <group
//                           name="Drone_Gen_R"
//                           position={[-19.23712921, -26.57673073, -0.74819756]}
//                           rotation={[Math.PI / 2, -1.02974445, Math.PI / 2]}>
//                           <mesh
//                             name="0"
//                             castShadow
//                             receiveShadow
//                             geometry={nodes['0'].geometry}
//                             material={materials.body}
//                             position={[-0.00000334, 0, 0.00000343]}
//                           />
//                           <group
//                             name="Drone_Panel_R"
//                             position={[0.67849636, -0.37505692, 1.95787477]}>
//                             <group
//                               name="Drone_leg_R"
//                               position={[-12.88695049, -9.61081028, -0.72928911]}
//                               rotation={[-1.23918403, Math.PI / 2, 0]}>
//                               <mesh
//                                 name="Drone_leg_R_leg_0"
//                                 castShadow
//                                 receiveShadow
//                                 geometry={nodes.Drone_leg_R_leg_0.geometry}
//                                 material={materials.material}
//                                 position={[0, 0, -0.00000205]}
//                               />
//                               <group
//                                 name="R_P1_G"
//                                 position={[2.41547394, -4.84228849, -0.0066543]}
//                                 rotation={[-Math.PI, 1.30899676, -Math.PI]}>
//                                 <mesh
//                                   name="R_P1_G_leg_0"
//                                   castShadow
//                                   receiveShadow
//                                   geometry={nodes.R_P1_G_leg_0.geometry}
//                                   material={materials.material}
//                                   position={[-0.00000215, 0, 0]}
//                                 />
//                                 <group name="R_P2" rotation={[1.3343986, 0, 0]}>
//                                   <mesh
//                                     name="R_P2_leg_0"
//                                     castShadow
//                                     receiveShadow
//                                     geometry={nodes.R_P2_leg_0.geometry}
//                                     material={materials.material}
//                                     position={[0, 0.00000393, -0.00001884]}
//                                   />
//                                   <group
//                                     name="R_P3_G"
//                                     position={[0.00268936, -22.91636467, 0.02692011]}>
//                                     <mesh
//                                       name="R_P3_G_leg_0"
//                                       castShadow
//                                       receiveShadow
//                                       geometry={nodes.R_P3_G_leg_0.geometry}
//                                       material={materials.material}
//                                       position={[0, 0.00000516, -0.00001973]}
//                                     />
//                                     <group
//                                       name="R_P4"
//                                       position={[0.00490379, 0.00297368, -0.00145558]}
//                                       rotation={[1.29471751, 2e-8, -Math.PI]}>
//                                       <mesh
//                                         name="R_P4_leg_0"
//                                         castShadow
//                                         receiveShadow
//                                         geometry={nodes.R_P4_leg_0.geometry}
//                                         material={materials.material}
//                                         position={[0, -0.00000536, 0]}
//                                       />
//                                       <group
//                                         name="R_P5_M"
//                                         position={[0.01078343, -11.28592968, 0.08222936]}
//                                         rotation={[0.00000639, 0, 0]}>
//                                         <mesh
//                                           name="R_P5_M_leg_0"
//                                           castShadow
//                                           receiveShadow
//                                           geometry={nodes.R_P5_M_leg_0.geometry}
//                                           material={materials.material}
//                                           position={[0, -0.00002577, 0.00000317]}
//                                         />
//                                         <group
//                                           name="R_P6_G"
//                                           position={[-0.00579487, -9.3260498, -0.08199392]}>
//                                           <mesh
//                                             name="R_P6_G_leg_0"
//                                             castShadow
//                                             receiveShadow
//                                             geometry={nodes.R_P6_G_leg_0.geometry}
//                                             material={materials.material}
//                                             position={[0, -0.00002389, 0]}
//                                           />
//                                           <group
//                                             name="R_P7"
//                                             position={[0, -0.00002403, 0]}
//                                             rotation={[1.41077029, 0, 0]}>
//                                             <mesh
//                                               name="R_P7_leg_0"
//                                               castShadow
//                                               receiveShadow
//                                               geometry={nodes.R_P7_leg_0.geometry}
//                                               material={materials.material}
//                                               position={[0, 0, -0.0000055]}
//                                             />
//                                           </group>
//                                         </group>
//                                       </group>
//                                     </group>
//                                   </group>
//                                 </group>
//                               </group>
//                             </group>
//                             <mesh
//                               name="Drone_Panel_R_body_0"
//                               castShadow
//                               receiveShadow
//                               geometry={nodes.Drone_Panel_R_body_0.geometry}
//                               material={materials.body}
//                               position={[0.00000244, -0.00000268, 0]}
//                             />
//                           </group>
//                         </group>
//                         <group name="Drone_ILens" position={[0, -14.96581173, 41.50517273]}>
//                           <group
//                             name="Drone_IEye"
//                             position={[0, -0.01823282, -8.90852165]}
//                             rotation={[-3.10854151, 0, -Math.PI]}>
//                             <mesh
//                               name="1"
//                               castShadow
//                               receiveShadow
//                               geometry={nodes['1'].geometry}
//                               material={materials.body}
//                               position={[0, -0.00000286, 0.00000668]}
//                             />
//                           </group>
//                           <mesh
//                             name="Drone_ILens_body_0"
//                             castShadow
//                             receiveShadow
//                             geometry={nodes.Drone_ILens_body_0.geometry}
//                             material={materials.body}
//                             position={[0, -0.00000286, 0.00000668]}
//                           />
//                         </group>
//                         <group name="Drone_leg_F" position={[0, -38.68080139, 20.01195145]}>
//                           <mesh
//                             name="Drone_leg_F_leg_0"
//                             castShadow
//                             receiveShadow
//                             geometry={nodes.Drone_leg_F_leg_0.geometry}
//                             material={materials.material}
//                             position={[0, 0.00000334, 0]}
//                           />
//                           <group
//                             name="F_P1_G"
//                             position={[0.00663002, -5.51049137, -0.09274387]}
//                             rotation={[0, Math.PI / 2, 0]}>
//                             <mesh
//                               name="F_P1_G_leg_0"
//                               castShadow
//                               receiveShadow
//                               geometry={nodes.F_P1_G_leg_0.geometry}
//                               material={materials.material}
//                               position={[0, -0.0000186, 0]}
//                             />
//                             <group
//                               name="F_P2"
//                               position={[0, -0.00005102, 0]}
//                               rotation={[Math.PI / 2, 0.08726648, -Math.PI / 2]}>
//                               <mesh
//                                 name="F_P2_leg_0"
//                                 castShadow
//                                 receiveShadow
//                                 geometry={nodes.F_P2_leg_0.geometry}
//                                 material={materials.material}
//                               />
//                               <group
//                                 name="F_P3_G"
//                                 position={[0.00007689, -22.91588974, 0.02676392]}>
//                                 <mesh
//                                   name="F_P3_G_leg_0"
//                                   castShadow
//                                   receiveShadow
//                                   geometry={nodes.F_P3_G_leg_0.geometry}
//                                   material={materials.material}
//                                   position={[0, 0, 0.00000573]}
//                                 />
//                                 <group
//                                   name="F_P4"
//                                   position={[0, 0, 0.00000573]}
//                                   rotation={[1.22173066, 0, -Math.PI]}>
//                                   <mesh
//                                     name="F_P4_leg_0"
//                                     castShadow
//                                     receiveShadow
//                                     geometry={nodes.F_P4_leg_0.geometry}
//                                     material={materials.material}
//                                     position={[0, 0.00001334, -0.00000477]}
//                                   />
//                                   <group
//                                     name="F_P5_M"
//                                     position={[-0.01574668, -11.28273296, 0.08171558]}>
//                                     <mesh
//                                       name="F_P5_M_leg_0"
//                                       castShadow
//                                       receiveShadow
//                                       geometry={nodes.F_P5_M_leg_0.geometry}
//                                       material={materials.material}
//                                       position={[0, 0.00000764, 0]}
//                                     />
//                                     <group
//                                       name="F_P6_G"
//                                       position={[0.00542223, -9.32614803, -0.0821743]}>
//                                       <mesh
//                                         name="F_P6_G_leg_0"
//                                         castShadow
//                                         receiveShadow
//                                         geometry={nodes.F_P6_G_leg_0.geometry}
//                                         material={materials.material}
//                                         position={[0, 0.00000859, 0]}
//                                       />
//                                       <group
//                                         name="F_P7"
//                                         position={[0, 0.00004197, 0.00000763]}
//                                         rotation={[1.26006213, 0, 0]}>
//                                         <mesh
//                                           name="F_P7_leg_0"
//                                           castShadow
//                                           receiveShadow
//                                           geometry={nodes.F_P7_leg_0.geometry}
//                                           material={materials.material}
//                                           position={[0, -0.00000763, -0.00000382]}
//                                         />
//                                       </group>
//                                     </group>
//                                   </group>
//                                 </group>
//                               </group>
//                             </group>
//                           </group>
//                         </group>
//                         <group
//                           name="Drone_Turb_M_L"
//                           position={[19.97339821, 24.55684853, -6.00704527]}
//                           rotation={[-1.42651861, 0.3656856, Math.PI / 2]}>
//                           <group
//                             name="Drone_Turb_Blade_L"
//                             position={[-0.0000239, -36.15513992, -10.96676159]}
//                             rotation={[1.86530357, 0, 0]}>
//                             <mesh
//                               name="Drone_Turb_Blade_L_body_0"
//                               castShadow
//                               receiveShadow
//                               geometry={nodes.Drone_Turb_Blade_L_body_0.geometry}
//                               material={materials.body}
//                               position={[-0.00000374, -0.00000852, 0.0000053]}
//                             />
//                           </group>
//                           <mesh
//                             name="Drone_Turb_M_L_body_0"
//                             castShadow
//                             receiveShadow
//                             geometry={nodes.Drone_Turb_M_L_body_0.geometry}
//                             material={materials.body}
//                           />
//                         </group>
//                         <group
//                           name="Drone_Turb_M_R"
//                           position={[-19.97339821, 24.55684662, -6.00704813]}
//                           rotation={[-1.42651841, -0.36568597, -Math.PI / 2]}>
//                           <group
//                             name="Drone_Turb_Blade_R"
//                             position={[0.00005104, -36.15515518, -10.96674728]}
//                             rotation={[1.86530357, 0, 0]}>
//                             <mesh
//                               name="Drone_Turb_Blade_R_body_0"
//                               castShadow
//                               receiveShadow
//                               geometry={nodes.Drone_Turb_Blade_R_body_0.geometry}
//                               material={materials.body}
//                               position={[0.00000202, 0.00001156, -0.00000608]}
//                             />
//                           </group>
//                           <mesh
//                             name="Drone_Turb_M_R_body_0"
//                             castShadow
//                             receiveShadow
//                             geometry={nodes.Drone_Turb_M_R_body_0.geometry}
//                             material={materials.body}
//                           />
//                         </group>
//                         <group
//                           name="Drone_UPanel_L"
//                           position={[22.44218254, -9.64864349, -0.0769465]}
//                           rotation={[Math.PI / 2, 1.30439212, -Math.PI / 2]}>
//                           <mesh
//                             name="Drone_UPanel_L_body_0"
//                             castShadow
//                             receiveShadow
//                             geometry={nodes.Drone_UPanel_L_body_0.geometry}
//                             material={materials.body}
//                             position={[0, 0.00000349, 0.00000719]}
//                           />
//                         </group>
//                         <group
//                           name="Drone_UPanel_R"
//                           position={[-22.55685997, -8.62517166, 0.14467257]}
//                           rotation={[Math.PI / 2, -1.30439212, Math.PI / 2]}>
//                           <mesh
//                             name="Drone_UPanel_R_body_0"
//                             castShadow
//                             receiveShadow
//                             geometry={nodes.Drone_UPanel_R_body_0.geometry}
//                             material={materials.body}
//                             position={[0, 0.00000492, 0.0000039]}
//                           />
//                         </group>
//                         <group name="Drone_UPart" position={[0, 33.47654724, -3.07304811]}>
//                           <mesh
//                             name="Drone_UPart_body_0"
//                             castShadow
//                             receiveShadow
//                             geometry={nodes.Drone_UPart_body_0.geometry}
//                             material={materials.body}
//                           />
//                         </group>
//                       </group>
//                     </group>
//                     <group
//                       name="Eye_Controller"
//                       position={[0, 143.07284546, 58.63672638]}
//                       rotation={[0.03466401, 0, 0]}>
//                       <group
//                         name="Eye_Pupil"
//                         position={[0, -0.00002384, 0]}
//                         rotation={[-Math.PI / 2, 0, 0]}
//                       />
//                     </group>
//                   </group>
//                 </group>
//                 <group name="Env">
//                   <group name="Himmel" />
//                   <group
//                     name="Scheibe"
//                     position={[0, -98.99999237, 0]}
//                     rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
//                     <mesh
//                       name="Scheibe_Boden_0"
//                       castShadow
//                       receiveShadow
//                       geometry={nodes.Scheibe_Boden_0.geometry}
//                       material={materials.Boden}
//                       position={[0, 0, -0.00000763]}
//                     />
//                   </group>
//                 </group>
//               </group>
//             </group>
//           </group>
//         </group>
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/buster_drone.glb')